device_asn: "{{ leaf_asn_base + (inventory_hostname.split('_')[-1] | int) }}"

# Leaf ASN base
leaf_asn_base: 65101

# Loopback router-id / VTEP source
loopback_ip: "{{ '172.16.1.0' if inventory_hostname == 'Leaf_Router_1' else '172.16.1.1' }}"

# VLANs hacia servidores
evpn_vlans:
  - vlan: 10
    name: SERV_10
  - vlan: 20
    name: SERV_20
  - vlan: 30
    name: SERV_30

# Offset VXLAN
vxlan_offset: 1000

# Interfaces hacia servidores
server_interfaces:
  - Ethernet3
  - Ethernet4

# Vecinos EVPN (spines / route reflectors)
evpn_rr_neighbors:
  - ip: 10.0.1.138
    asn: 65000
  - ip: 10.0.1.140
    asn: 65000

server_access_ports:
  Leaf_Router_1:
    - name: Ethernet3
      description: "Server1 eth0"
      vlan: 10

  Leaf_Router_2:
    - name: Ethernet4
      description: "Server2 eth1"
      vlan: 10

