device_asn: "{{ spine_asn }}"

# Spine ASN
spine_asn: 65000

# Vecinos EVPN: todos los leafs
evpn_leaf_neighbors:
  - ip: 10.0.1.139
    asn: 65101
  - ip: 10.0.1.141
    asn: 65102

loopback_ip: 172.16.0.0

