---
- name: Deploy Overlay VXLAN EVPN
  hosts: spines,leafs
  gather_facts: no
  collections:
    - arista.eos

  tasks:
    - name: Configurar VXLAN / VNIs
      include_tasks: tasks/overlay/vxlan.yml

    - name: Configurar SVIs Anycast en leafs
      include_tasks: tasks/overlay/svis.yml
      when: inventory_hostname in groups['leafs']

    - name: Configurar puertos de acceso hacia servidores
      include_tasks: tasks/access.yml
      when: inventory_hostname in groups['leafs']

